from datetime import date

from agx_research.acquisition_intelligence.config_generation import generate_source_spec, suggest_collector
from agx_research.acquisition_intelligence.historical import HistoricalAvailabilityAssessment
from agx_research.acquisition_intelligence.legality import LegalityAssessment, LegalityVerdict
from agx_research.acquisition_intelligence.ranking import RankedMethod
from agx_research.acquisition_intelligence.stability import StabilityAssessment
from agx_research.acquisition_intelligence.target import TargetOrganization
from agx_research.discovery.candidate import DiscoveryMethod, SourceCandidate
from agx_research.sources.spec import AccessMethod, LifecycleState, SourceCategory, SourceStatus


def make_candidate(url: str, access_method: AccessMethod) -> SourceCandidate:
    return SourceCandidate(
        discovered_url=url, origin_page_url="https://example.com",
        discovery_method=DiscoveryMethod.RSS_AUTODISCOVERY, access_method_guess=access_method,
    )


def make_ranked(url: str, access_method: AccessMethod, *, composite=0.7) -> RankedMethod:
    return RankedMethod(
        candidate=make_candidate(url, access_method),
        legality=LegalityAssessment(verdict=LegalityVerdict.ALLOWED),
        stability=StabilityAssessment(score=composite),
        historical=HistoricalAvailabilityAssessment(
            score=composite, has_any_snapshot=True, snapshot_count=10,
            earliest_snapshot=date(2020, 1, 1),
        ),
        composite_score=composite,
    )


def test_suggest_collector_rss():
    assert suggest_collector(make_candidate("https://x/feed.xml", AccessMethod.RSS_FEED)) == "RssNewsCollector"


def test_suggest_collector_excel():
    result = suggest_collector(make_candidate("https://x/bulletin.xlsx", AccessMethod.CSV_DOWNLOAD))
    assert "ExcelSeriesCollector" in result


def test_suggest_collector_pdf():
    result = suggest_collector(make_candidate("https://x/report.pdf", AccessMethod.PDF_DOWNLOAD))
    assert "PdfDocumentCollector" in result


def test_suggest_collector_plain_csv_or_json_needs_inspection():
    assert suggest_collector(make_candidate("https://x/data.csv", AccessMethod.CSV_DOWNLOAD)) is None
    assert suggest_collector(make_candidate("https://x/api", AccessMethod.JSON_API)) is None


def test_generated_spec_always_planned_never_implemented():
    target = TargetOrganization(id="t1", name="Test Org", category=SourceCategory.NEWS)
    ranked = make_ranked("https://x/feed.xml", AccessMethod.RSS_FEED, composite=0.95)
    spec = generate_source_spec(target, ranked)

    assert spec.status == SourceStatus.PLANNED  # never auto-flipped, however high the score
    assert spec.lifecycle_state == LifecycleState.CANDIDATE
    assert spec.collector == "RssNewsCollector"
    assert spec.base_url == "https://x/feed.xml"
    assert "Auto-generated by AcquisitionIntelligenceEngine" in spec.notes


def test_generated_spec_uses_existing_source_id_when_linked():
    target = TargetOrganization(
        id="new_id_for_target", name="Test Org", category=SourceCategory.NEWS,
        existing_source_id="reuters",
    )
    ranked = make_ranked("https://x/feed.xml", AccessMethod.RSS_FEED)
    spec = generate_source_spec(target, ranked)
    assert spec.id == "reuters"


def test_reliability_prior_scales_with_composite_but_stays_capped():
    target = TargetOrganization(id="t1", name="Test Org", category=SourceCategory.NEWS)
    low = generate_source_spec(target, make_ranked("https://x", AccessMethod.RSS_FEED, composite=0.0))
    high = generate_source_spec(target, make_ranked("https://x", AccessMethod.RSS_FEED, composite=1.0))
    assert low.reliability_score < high.reliability_score
    assert high.reliability_score <= 0.75
