"""Config generation: turn a selected, ranked acquisition method into a real
`SourceSpec` -- the "automatically generate the appropriate collector
configuration" step.

Crucial honesty boundary: the generated spec's `status` always stays
`PLANNED`, never `IMPLEMENTED`, even when a fully generic collector class is
suggested. Matching `AD-16`/`Collector.__init__`'s IMPLEMENTED gate,
becoming collectable requires an engineer to actually instantiate, wire, and
test that collector against this specific endpoint -- auto-generation
produces the *configuration a human/engineer finishes in minutes*, not a
silent claim that untested code is production-ready.
"""

from __future__ import annotations

from datetime import datetime

from agx_research.acquisition_intelligence.ranking import RankedMethod
from agx_research.acquisition_intelligence.target import TargetOrganization
from agx_research.discovery.candidate import SourceCandidate
from agx_research.sources.spec import (
    AccessMethod,
    SourceSpec,
    SourceStatus,
    default_lifecycle_for_status,
)

_MIN_PRIOR = 0.3
_MAX_PRIOR = 0.75  # auto-discovered sources cap below any hand-verified IMPLEMENTED prior


def suggest_collector(candidate: SourceCandidate) -> str | None:
    """Which existing generic collector class would serve this method, if any
    is unambiguous from the URL/access-method alone. `None` means the method
    is real but needs schema-specific engineering before a collector exists.
    """
    url = candidate.discovered_url.lower()
    if candidate.access_method_guess == AccessMethod.RSS_FEED:
        return "RssNewsCollector"
    if url.endswith((".xlsx", ".xls")):
        return "ExcelSeriesCollector (column mapping still needs configuring)"
    if url.endswith(".pdf"):
        return "PdfDocumentCollector (subclass required: source-specific parse())"
    return None  # plain CSV/JSON API/sitemap: schema must be inspected first


def _derived_prior(composite_score: float) -> float:
    return round(_MIN_PRIOR + (_MAX_PRIOR - _MIN_PRIOR) * composite_score, 2)


def generate_source_spec(target: TargetOrganization, ranked: RankedMethod) -> SourceSpec:
    candidate = ranked.candidate
    collector = suggest_collector(candidate)
    status = SourceStatus.PLANNED
    lifecycle_state, activation_status = default_lifecycle_for_status(status)
    prior = _derived_prior(ranked.composite_score)

    return SourceSpec(
        id=target.existing_source_id or target.id,
        name=target.name,
        category=target.category,
        country=target.country,
        access_method=candidate.access_method_guess,
        status=status,
        lifecycle_state=lifecycle_state,
        activation_status=activation_status,
        base_url=candidate.discovered_url,
        reliability_score=prior,
        freshness_score=0.5,  # unmeasured until real collection begins
        historical_coverage=(
            f"{ranked.historical.snapshot_count} Wayback snapshot(s) since "
            f"{ranked.historical.earliest_snapshot}" if ranked.historical.has_any_snapshot
            else "no archived history found"
        ),
        collector=collector,
        license="Unverified -- auto-discovered; confirm license/redistribution terms before "
        "production use.",
        terms_of_use_url=None,
        conflict_priority=40,  # below every hand-verified source until measured otherwise
        notes=(
            f"Auto-generated by AcquisitionIntelligenceEngine on "
            f"{datetime.now().isoformat()}. Discovered via "
            f"{candidate.discovery_method.value} at {candidate.origin_page_url}. "
            f"Legality: {ranked.legality.verdict.value} ({ranked.legality.evidence}). "
            f"Stability score: {ranked.stability.score:.2f}. "
            f"Historical availability score: {ranked.historical.score:.2f}. "
            f"Suggested collector: {collector or 'none yet -- schema inspection needed'}."
        ),
    )
